export const INDUSTRIES = [
  'Information Technology',
  'Banking & Financial Services',
  'Telecommunications',
  'Garments & Textile',
  'Pharmaceuticals',
  'FMCG',
  'Real Estate & Construction',
  'Media & Entertainment',
  'Education',
  'Healthcare',
  'Agriculture',
  'Energy & Power',
  'NGO / Development',
  'Government / Public Sector',
  'Retail & E-commerce',
  'Manufacturing',
  'Logistics & Transportation',
  'Hotel & Hospitality',
  'Legal Services',
  'Consulting',
  'Insurance',
  'Automotive',
  'Food & Beverage',
  'Chemicals',
  'International Organization',
  'Startup',
  'Other',
] as const;

export type Industry = (typeof INDUSTRIES)[number];
